# Generated by Django 4.2.11 on 2024-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_options_alter_filmwork_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'Actor'), ('writer', 'Writer'), ('director', 'Director')], verbose_name='role'),
        ),
    ]
