# Generated by Django 4.2.11 on 2024-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('movie', 'Movie'), ('ТВ-шоу', 'TV Show')], verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('актер', 'Actor'), ('сценарист', 'Writer'), ('режиссер', 'Director')], verbose_name='role'),
        ),
    ]
