version: '3.8'
volumes:
  pgdbdata:
  static:
  media:
  esdata:

services:
  pgdb:
    image: postgres:15
    env_file:
      - .env
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  etl:
    container_name: etl
    build: ./
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
      pgdb:
        condition: service_healthy
    environment:
      - COMPOSE_BUILD_NO_CACHE=1
    command:
      - python
      - main.py
